#!/usr/bin/env python3
"""⚠️ SUPERSEDED 2026-08-27 — DO NOT RUN WITHOUT READING THIS.

Universal Screens' icons now come from the SUITE'S canonical mark, generated by
    backoffice/universal-platform/scripts/app-marks/desktop-icons.mjs Universal_Screens
which writes every surface at once (Windows .png/.ico, macOS .icns, Linux,
Android, the iOS asset catalog) plus a separate sealed installer icon.

This script still draws the older laptop-and-phone artwork, and running it will
OVERWRITE the generated icons with it. Kept because the drawing is the only
record of that artwork; if the mark is ever revised, revise it in marks.mjs.
"""

"""Generate the iOS asset-catalog images from the shared app-icon artwork.

Reuses `render_icon()` from make-app-icon.py (single source of truth) and writes:
  apps/ios/ScreenExtender/Assets.xcassets/AppIcon.appiconset/icon-1024.png  (opaque)
  apps/ios/ScreenExtender/Assets.xcassets/AppLogo.imageset/logo.png         (RGBA, in-app)

The .xcassets Contents.json files are committed alongside; only the PNGs are
regenerated here. Run after changing the artwork:  python scripts/make-ios-icons.py
"""
import importlib.util
import os

HERE = os.path.dirname(__file__)

# Load make-app-icon.py (hyphens → can't `import` directly) for render_icon().
_spec = importlib.util.spec_from_file_location(
    "make_app_icon", os.path.join(HERE, "make-app-icon.py")
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

ASSETS = os.path.abspath(
    os.path.join(HERE, "..", "apps", "ios", "ScreenExtender", "Assets.xcassets")
)


def main() -> None:
    # App icon: a single 1024 universal icon (Xcode 14+ single-size slot). iOS app
    # icons must be opaque (no alpha) — render_icon(opaque=True) handles that.
    appicon = os.path.join(ASSETS, "AppIcon.appiconset", "icon-1024.png")
    _mod.render_icon(1024, opaque=True).save(appicon)
    print("wrote", appicon)

    # In-app logo (shown on the home screen, like Android's app_icon). Keep the
    # rounded-square on a transparent canvas so it reads as a tile at any size.
    logo = os.path.join(ASSETS, "AppLogo.imageset", "logo.png")
    _mod.render_icon(512, opaque=False).save(logo)
    print("wrote", logo)


if __name__ == "__main__":
    main()
