#!/usr/bin/env python3
"""⚠️ SUPERSEDED 2026-08-27 — DO NOT RUN WITHOUT READING THIS.

Universal Screens' icons now come from the SUITE'S canonical mark, generated by
    backoffice/universal-platform/scripts/app-marks/desktop-icons.mjs Universal_Screens
which writes every surface at once (Windows .png/.ico, macOS .icns, Linux,
Android, the iOS asset catalog) plus a separate sealed installer icon.

This script still draws the older laptop-and-phone artwork, and running it will
OVERWRITE the generated icons with it. Kept because the drawing is the only
record of that artwork; if the mark is ever revised, revise it in marks.mjs.
"""

"""Generate the macOS .icns from the shared app-icon artwork.

Reuses `render_icon()` from make-app-icon.py (single source of truth) and writes:
  crates/host-macos/assets/AppIcon.icns

Every size is *rendered* rather than downsampled from one large PNG, for the same
reason make-win-ico.py does it: the small entries are the ones the system actually
shows most (16/32 px in the Finder list view and the menu bar), and a LANCZOS
downsample of a 1024 px drawing turns their hairlines to mush.

⚠️ Rounded corners are OURS to draw, not the system's. macOS does NOT mask app
icons the way iOS does — whatever is in the .icns is what appears in the Dock. So
this uses `opaque=False`, keeping render_icon's rounded-square on a transparent
canvas. Passing opaque=True (the iOS setting) would put a hard-cornered square in
the Dock next to every rounded one.

`iconutil` (macOS-only) is used when it is there. Off macOS — a Linux CI box, or
whoever is editing the artwork that day — `write_icns()` below assembles the same
container by hand, so the committed .icns never goes stale just because nobody had
a Mac handy.

Run after changing the artwork:  python3 scripts/make-mac-icns.py
"""
import importlib.util
import io
import os
import shutil
import struct
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "..", "crates", "host-macos", "assets")
OUT = os.path.join(OUT_DIR, "AppIcon.icns")

# Load make-app-icon.py (hyphens → can't `import` directly) for render_icon().
_spec = importlib.util.spec_from_file_location(
    "make_app_icon", os.path.join(HERE, "make-app-icon.py")
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

# The .iconset names macOS expects. Each (base, scale) renders at base*scale px.
# 16 through 512@2x = 1024 is the full set `iconutil` accepts; omitting any of
# them makes the icon fall back to a scaled neighbour in that context.
SIZES = [
    (16, 1), (16, 2),
    (32, 1), (32, 2),
    (128, 1), (128, 2),
    (256, 1), (256, 2),
    (512, 1), (512, 2),
]

# The icns element type for each (base, scale), for the no-iconutil path — the
# same set iconutil emits: PNG payloads throughout, except the 16 and 32 px 1x
# entries, which it writes as raw ARGB. Matching it keeps the hand-built file to
# a shape every macOS already reads.
ICNS_TYPES = {
    (16, 1): "ic04", (16, 2): "ic11",
    (32, 1): "ic05", (32, 2): "ic12",
    (128, 1): "ic07", (128, 2): "ic13",
    (256, 1): "ic08", (256, 2): "ic14",
    (512, 1): "ic09", (512, 2): "ic10",
}


def _rle24(channel: bytes) -> bytes:
    """PackBits-style RLE, in the variant icns uses for its raw-pixel elements.

    Control byte < 0x80 → the next (n + 1) bytes are literal; >= 0x80 → the next
    byte repeats (n - 125) times. So runs are 3..130 long and literals 1..128.
    """
    out = bytearray()
    i, n = 0, len(channel)
    while i < n:
        run = 1
        while i + run < n and channel[i + run] == channel[i] and run < 130:
            run += 1
        if run >= 3:
            out.append(run + 125)
            out.append(channel[i])
            i += run
            continue
        # No run worth encoding — gather literals until one starts.
        start = i
        while i < n and i - start < 128:
            if i + 2 < n and channel[i] == channel[i + 1] == channel[i + 2]:
                break
            i += 1
        out.append(i - start - 1)
        out += channel[start:i]
    return bytes(out)


def _argb_element(img) -> bytes:
    """An 'ARGB' payload: the magic, then each channel RLE'd in A, R, G, B order."""
    channels = (img.getchannel(c).tobytes() for c in "ARGB")
    return b"ARGB" + b"".join(_rle24(ch) for ch in channels)


def write_icns(images: dict, path: str) -> None:
    """Write `{(base, scale): PIL image}` as an .icns, without iconutil.

    The container is trivial: 'icns', the total byte length, then one element per
    entry — a 4-char type, the element's own length (header included), payload.
    """
    body = bytearray()
    for key, img in images.items():
        kind = ICNS_TYPES[key]
        if kind in ("ic04", "ic05"):
            payload = _argb_element(img)
        else:
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            payload = buf.getvalue()
        body += kind.encode("ascii") + struct.pack(">I", len(payload) + 8) + payload
    with open(path, "wb") as f:
        f.write(b"icns" + struct.pack(">I", len(body) + 8) + bytes(body))


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    images = {}
    for base, scale in SIZES:
        px = base * scale
        images[(base, scale)] = _mod.render_icon(px, opaque=False)
        print(f"  rendered {base}x{base}{'' if scale == 1 else '@2x'} ({px}px)")

    if shutil.which("iconutil"):
        with tempfile.TemporaryDirectory() as tmp:
            iconset = os.path.join(tmp, "AppIcon.iconset")
            os.makedirs(iconset)
            for (base, scale), img in images.items():
                suffix = "" if scale == 1 else "@2x"
                img.save(os.path.join(iconset, f"icon_{base}x{base}{suffix}.png"))
            subprocess.run(
                ["iconutil", "-c", "icns", iconset, "-o", os.path.abspath(OUT)],
                check=True,
            )
    else:
        write_icns(images, os.path.abspath(OUT))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
